In [71]:
import numpy as np
import torch
from torch import nn
from tests_backpropagation import main_test

torch.manual_seed(123)
torch.set_default_dtype(torch.double)

## Class ``MyNet``

Read carefully how ``MyNet`` is implemented in the cell below. In particular:  
- ``n_hid`` is a list of integer, representing the number of hidden units in each hidden layer.   
-  ``MyNet([2, 3, 2]) = MiniNet()`` where ``MiniNet`` is the neural network defined in the fourth tutorial, in which notations are also clarified.     
- ``model.L`` is the number of hidden layers, ``L``   
- ``model.f[l]`` is the activation function of layer ``l``, $f^{[l]}$ (here ``torch.tanh``)   
- ``model.df[l]`` is the derivative of the activation function, $f'^{[l]}$   
- ``model.a[l]``  is the tensor $A^{[l]}$, (shape: ``(1, n(l))``)   
- ``model.z[l]``  is the tensor $Z^{[l]}$, (shape: ``(1, n(l))``)  
- Weights $W^{[l]}$ (shape: ``(n(l+1), n(l))``) and biases $\mathbf{b}^{[l]}$ (shape: ``(n(l+1))``) can be accessed as follows:
```
weights = model.fc[str(l)].weight.data
bias = model.fc[str(l)].bias.data
```

In [72]:
class MyNet(nn.Module):
    def __init__(self, n_l = [2, 3, 2]):
        super().__init__() 
        
        
        # number of layers in our network (following Andrew's notations)
        self.L = len(n_l)-1
        self.n_l = n_l
        
        # Where we will store our neuron values
        # - z: before activation function 
        # - a: after activation function (a=f(z))
        self.z = {i : None for i in range(1, self.L+1)}
        self.a = {i : None for i in range(self.L+1)}

        # Where we will store the gradients for our custom backpropagation algo
        self.dL_dw = {i : None for i in range(1, self.L+1)}
        self.dL_db = {i : None for i in range(1, self.L+1)}

        # Our activation functions
        self.f = {i : lambda x : torch.tanh(x) for i in range(1, self.L+1)}

        # Derivatives of our activation functions
        self.df = {
            i : lambda x : (1 / (torch.cosh(x)**2)) 
            for i in range(1, self.L+1)
        }
        
        # fully connected layers
        # We have to use nn.ModuleDict and to use strings as keys here to 
        # respect pytorch requirements (otherwise, the model does not learn)
        self.fc = nn.ModuleDict({str(i): None for i in range(1, self.L+1)})
        for i in range(1, self.L+1):
            self.fc[str(i)] = nn.Linear(in_features=n_l[i-1], out_features=n_l[i])
        
    def forward(self, x):
        # Input layer
        self.a[0] = torch.flatten(x, 1)
        
        # Hidden layers until output layer
        for i in range(1, self.L+1):

            # fully connected layer
            self.z[i] = self.fc[str(i)](self.a[i-1])
            # activation
            self.a[i] = self.f[i](self.z[i])

        # return output
        return self.a[self.L]

## Tasks

Write a function ``backpropagation(model, y_true, y_pred)`` that computes:

- $\frac{\partial L}{\partial w^{[l]}_{i,j}}$ and store them in ``model.dL_dw[l][i,j]`` for $l \in [1 .. L]$ 
- $\frac{\partial L}{\partial b^{[l]}_{j}}$ and store them in ``model.dL_db[l][j]`` for $l \in [1 .. L]$ 

assuming ``model`` is an instance of the ``MyNet`` class.

A vectorized implementation would be appreciated.

In [106]:
def backpropagation(model: MyNet, y_true, y_pred):
    #model.fc[model.L]

    #Bias in last layer
    db = (-2*(y_true - y_pred)) * model.df[model.L](model.z[model.L])
    model.dL_db[model.L] = db[0]

    #print(f'bias: {model.fc[str(model.L)].bias.data}')
    #print(f'dbias: {model.dL_db[model.L].data}')
    
    #Weight in last layer
    model.dL_dw[model.L] = (model.a[model.L-1].T @ db).T

    #print(f'weights: {model.fc[str(model.L)].weight.data}')
    #print(f'dweights: {model.dL_dw[model.L].data}')


    for l in range(model.L-1, 0, -1):
        #Update bias
        db = (((model.fc[str(l+1)].weight.data).T @ (db.T)).T * model.df[l](model.z[l]))
        model.dL_db[l] = db[0]

        #print(f'bias: {model.fc[str(l)].bias.data}')
        #print(f'dbias: {model.dL_db[l].data}')

        #Update weight
        model.dL_dw[l] = (model.a[l-1].T @ db).T

        #print(f'weights: {model.fc[str(l)].weight.data}')
        #print(f'dweights: {model.dL_dw[l].data}')


    return None

## Run the cells below, and check the output

- In the 1st cell, we use a toy dataset and the same architecture as the MiniNet class of the fourth tutorial. 
- In the 2nd cell, we use a few samples of the MNIST dataset with a consistent model architecture (``24x24`` black and white cropped images as input and ``10`` output classes). 

You can set ``verbose`` to ``True`` if you want more details about your computations versus what is expected.

In [107]:
model = MyNet([2, 3, 2])

main_test(backpropagation, model, verbose=True, data='toy')


 ========================  Check gradients ======================== 
tensor([[ 0.7641, -0.6987]], grad_fn=<MulBackward0>)
tensor([ 0.7641, -0.6987], grad_fn=<SelectBackward0>)
tensor([[-1.1053,  0.6603]], grad_fn=<MulBackward0>)
tensor([-1.1053,  0.6603], grad_fn=<SelectBackward0>)
tensor([[-3.9959,  4.0016]], grad_fn=<MulBackward0>)
tensor([-3.9959,  4.0016], grad_fn=<SelectBackward0>)
tensor([[-0.5633,  0.7045]], grad_fn=<MulBackward0>)
tensor([-0.5633,  0.7045], grad_fn=<SelectBackward0>)
tensor([[-0.5718,  0.6346]], grad_fn=<MulBackward0>)
tensor([-0.5718,  0.6346], grad_fn=<SelectBackward0>)
tensor([[-0.4721,  0.5259]], grad_fn=<MulBackward0>)
tensor([-0.4721,  0.5259], grad_fn=<SelectBackward0>)
tensor([[-0.4020,  0.4352]], grad_fn=<MulBackward0>)
tensor([-0.4020,  0.4352], grad_fn=<SelectBackward0>)
tensor([[-0.3495,  0.3701]], grad_fn=<MulBackward0>)
tensor([-0.3495,  0.3701], grad_fn=<SelectBackward0>)
tensor([[-0.3088,  0.3220]], grad_fn=<MulBackward0>)
tensor([-0.3088,  0.3

In [94]:
model = MyNet([24*24, 16, 10])
main_test(backpropagation, model, verbose=False, data='mnist')


 ========================  Check gradients ======================== 

 ================= Epoch 1 ================= 
Gradients consistent with autograd's computations. :) 
Gradients consistent with finite differences computations. :) 

 ==============  Check that weights have been updated ============= 
Weights have been updated. :)

 ===================  Check computational graph =================== 
All parameters seem correctly attached to the computational graph! :) 
